CREATE TABLE IF NOT EXISTS location (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude decimal(8,6) NOT NULL,  /*  ##.###### */
	longitude decimal(9,6) NOT NULL  /* ###.###### */
);

CREATE TABLE IF NOT EXISTS route (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_location_id int,
    end_location_id int,
	description varchar(200),
	CONSTRAINT fk_location_start FOREIGN KEY(start_location_id) REFERENCES location(id),
	CONSTRAINT fk_location_end FOREIGN KEY(end_location_id) REFERENCES location(id)
);

CREATE TABLE IF NOT EXISTS highlight (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	location_id int,
	name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    rating decimal(3,2) NOT NULL CHECK (rating>=0 AND rating<=5),
	CONSTRAINT fk_highlight_location FOREIGN KEY(location_id) REFERENCES location(id)
);

CREATE TABLE IF NOT EXISTS route_highlights (
    route_id int,
    highlight_id int,
	PRIMARY KEY(route_id, highlight_id),
	CONSTRAINT fk_routes_routeId FOREIGN KEY(route_id) REFERENCES route(id),
	CONSTRAINT fk_highlight_highlightId FOREIGN KEY(highlight_id) REFERENCES highlight(id)
);